import path from "path";
import sqlite3 from "sqlite3";

type Row = Record<string, unknown>;

const accessToken = process.env.SUPABASE_ACCESS_TOKEN;
const projectRef = process.env.SUPABASE_PROJECT_REF;
const dbUser = process.env.SUPABASE_DB_USER ?? "vintage_app";
const dbPassword = process.env.SUPABASE_DB_PASSWORD ?? "TempPass_2026_VintageInv!";
const sqliteDatabaseUrl = process.env.SQLITE_DATABASE_URL ?? "file:./prisma/dev.db";

if (!accessToken) {
  throw new Error("Missing SUPABASE_ACCESS_TOKEN");
}

if (!projectRef) {
  throw new Error("Missing SUPABASE_PROJECT_REF");
}

const sqliteFile = sqliteDatabaseUrl.startsWith("file:")
  ? sqliteDatabaseUrl.replace(/^file:/, "")
  : sqliteDatabaseUrl;
const sqlitePath = path.resolve(process.cwd(), sqliteFile);

function escapeLiteral(value: unknown): string {
  if (value === null || value === undefined) {
    return "NULL";
  }

  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error(`Invalid number literal: ${value}`);
    }
    return String(value);
  }

  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE";
  }

  return `'${String(value).replace(/'/g, "''")}'`;
}

function normalizeDateTime(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }

  if (typeof value === "number") {
    return new Date(value).toISOString();
  }

  if (typeof value === "string" && /^\d{13}$/.test(value)) {
    return new Date(Number(value)).toISOString();
  }

  return value;
}

function normalizeBoolean(value: unknown): unknown {
  if (value === null || value === undefined) {
    return value;
  }

  if (typeof value === "number") {
    return value !== 0;
  }

  if (typeof value === "string") {
    if (value === "0") {
      return false;
    }
    if (value === "1") {
      return true;
    }
  }

  return value;
}

function queryAll(database: sqlite3.Database, sql: string): Promise<Row[]> {
  return new Promise((resolve, reject) => {
    database.all(sql, (error, rows) => {
      if (error) {
        reject(error);
        return;
      }
      resolve(rows as Row[]);
    });
  });
}

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

function insertSql(
  tableName: string,
  columns: string[],
  rows: Row[],
  dateColumns: string[] = [],
  booleanColumns: string[] = []
): string[] {
  if (rows.length === 0) {
    return [];
  }

  return chunk(rows, 100).map((batch) => {
    const values = batch
      .map(
        (row) =>
          `(${columns
            .map((column) =>
              escapeLiteral(
                booleanColumns.includes(column)
                  ? normalizeBoolean(row[column])
                  : dateColumns.includes(column)
                    ? normalizeDateTime(row[column])
                    : row[column]
              )
            )
            .join(", ")})`
      )
      .join(",\n");

    return `INSERT INTO "${tableName}" (${columns.map((column) => `"${column}"`).join(", ")}) VALUES\n${values};`;
  });
}

async function main() {
  const database = new sqlite3.Database(sqlitePath, sqlite3.OPEN_READONLY);

  try {
    const [users, items, measurements, photos, sales] = await Promise.all([
      queryAll(database, 'SELECT "id", "username", "passwordHash", "createdAt" FROM "User" ORDER BY "id"'),
      queryAll(
        database,
        'SELECT "id", "itemId", "title", "category", "brand", "sizeTag", "condition", "yearEstimate", "color", "country", "notes", "cost", "targetPrice", "status", "createdAt", "updatedAt" FROM "Item" ORDER BY "id"'
      ),
      queryAll(
        database,
        'SELECT "id", "itemId", "pitToPit", "length" FROM "Measurement" ORDER BY "id"'
      ),
      queryAll(
        database,
        'SELECT "id", "itemId", "filePath", "isCover", "createdAt" FROM "Photo" ORDER BY "id"'
      ),
      queryAll(
        database,
        'SELECT "id", "saleId", "itemId", "platform", "sellPrice", "platformFee", "shippingCost", "netProfit", "saleDate", "createdAt" FROM "Sale" ORDER BY "id"'
      ),
    ]);

    const sqlParts = [
      `DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${dbUser}') THEN
    CREATE ROLE ${dbUser} LOGIN PASSWORD '${dbPassword}';
  ELSE
    ALTER ROLE ${dbUser} WITH LOGIN PASSWORD '${dbPassword}';
  END IF;
END $$;`,
      'DROP TABLE IF EXISTS "Sale" CASCADE;',
      'DROP TABLE IF EXISTS "Photo" CASCADE;',
      'DROP TABLE IF EXISTS "Measurement" CASCADE;',
      'DROP TABLE IF EXISTS "Item" CASCADE;',
      'DROP TABLE IF EXISTS "User" CASCADE;',
      `CREATE TABLE "User" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "username" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);`,
      `CREATE TABLE "Item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "itemId" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "brand" TEXT,
  "sizeTag" TEXT NOT NULL,
  "condition" TEXT NOT NULL,
  "yearEstimate" TEXT,
  "color" TEXT,
  "country" TEXT,
  "notes" TEXT,
  "cost" DOUBLE PRECISION NOT NULL,
  "targetPrice" DOUBLE PRECISION,
  "status" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);`,
      `CREATE TABLE "Measurement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "itemId" INTEGER NOT NULL,
  "pitToPit" DOUBLE PRECISION,
  "length" DOUBLE PRECISION,
  CONSTRAINT "Measurement_pkey" PRIMARY KEY ("id")
);`,
      `CREATE TABLE "Photo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "itemId" INTEGER NOT NULL,
  "filePath" TEXT NOT NULL,
  "isCover" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Photo_pkey" PRIMARY KEY ("id")
);`,
      `CREATE TABLE "Sale" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "saleId" TEXT NOT NULL,
  "itemId" INTEGER NOT NULL,
  "platform" TEXT NOT NULL,
  "sellPrice" DOUBLE PRECISION NOT NULL,
  "platformFee" DOUBLE PRECISION NOT NULL,
  "shippingCost" DOUBLE PRECISION NOT NULL,
  "netProfit" DOUBLE PRECISION NOT NULL,
  "saleDate" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Sale_pkey" PRIMARY KEY ("id")
);`,
      'CREATE UNIQUE INDEX "User_username_key" ON "User"("username");',
      'CREATE UNIQUE INDEX "Item_itemId_key" ON "Item"("itemId");',
      'CREATE UNIQUE INDEX "Measurement_itemId_key" ON "Measurement"("itemId");',
      'CREATE UNIQUE INDEX "Sale_itemId_key" ON "Sale"("itemId");',
      'ALTER TABLE "Measurement" ADD CONSTRAINT "Measurement_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      'ALTER TABLE "Photo" ADD CONSTRAINT "Photo_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      'ALTER TABLE "Sale" ADD CONSTRAINT "Sale_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;',
      ...insertSql("User", ["id", "username", "passwordHash", "createdAt"], users, ["createdAt"]),
      ...insertSql(
        "Item",
        [
          "id",
          "itemId",
          "title",
          "category",
          "brand",
          "sizeTag",
          "condition",
          "yearEstimate",
          "color",
          "country",
          "notes",
          "cost",
          "targetPrice",
          "status",
          "createdAt",
          "updatedAt",
        ],
        items,
        ["createdAt", "updatedAt"]
      ),
      ...insertSql("Measurement", ["id", "itemId", "pitToPit", "length"], measurements),
      ...insertSql(
        "Photo",
        ["id", "itemId", "filePath", "isCover", "createdAt"],
        photos,
        ["createdAt"],
        ["isCover"]
      ),
      ...insertSql(
        "Sale",
        ["id", "saleId", "itemId", "platform", "sellPrice", "platformFee", "shippingCost", "netProfit", "saleDate", "createdAt"],
        sales,
        ["saleDate", "createdAt"]
      ),
      `SELECT setval(pg_get_serial_sequence('"User"', 'id'), COALESCE((SELECT MAX("id") FROM "User"), 1), TRUE);`,
      `SELECT setval(pg_get_serial_sequence('"Item"', 'id'), COALESCE((SELECT MAX("id") FROM "Item"), 1), TRUE);`,
      `SELECT setval(pg_get_serial_sequence('"Measurement"', 'id'), COALESCE((SELECT MAX("id") FROM "Measurement"), 1), TRUE);`,
      `SELECT setval(pg_get_serial_sequence('"Photo"', 'id'), COALESCE((SELECT MAX("id") FROM "Photo"), 1), TRUE);`,
      `SELECT setval(pg_get_serial_sequence('"Sale"', 'id'), COALESCE((SELECT MAX("id") FROM "Sale"), 1), TRUE);`,
      `GRANT USAGE, CREATE ON SCHEMA public TO ${dbUser};`,
      `GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${dbUser};`,
      `GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${dbUser};`,
      `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${dbUser};`,
      `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${dbUser};`,
    ];

    const response = await fetch(
      `https://api.supabase.com/v1/projects/${projectRef}/database/query`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          query: sqlParts.join("\n"),
        }),
      }
    );

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`Supabase query failed (${response.status}): ${body}`);
    }

    console.log(
      JSON.stringify(
        {
          ok: true,
          projectRef,
          sqlitePath,
          counts: {
            users: users.length,
            items: items.length,
            measurements: measurements.length,
            photos: photos.length,
            sales: sales.length,
          },
          databaseUrl: `postgresql://${dbUser}:${dbPassword}@db.${projectRef}.supabase.co:5432/postgres?sslmode=require&connection_limit=1`,
          directUrl: `postgresql://${dbUser}:${dbPassword}@db.${projectRef}.supabase.co:5432/postgres?sslmode=require`,
        },
        null,
        2
      )
    );
  } finally {
    await new Promise<void>((resolve, reject) => {
      database.close((error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
